services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms
      MYSQL_USER: lms
      MYSQL_PASSWORD: lms
    ports:
      - "3306:3306"
    volumes:
      - lms_mysql_data:/var/lib/mysql

volumes:
  lms_mysql_data:
